-- =====================================================================================
-- Script de inicialización de esquema para el sistema escolar
-- =====================================================================================
-- CREATE TABLE statements for school modules under BOMERP_APP schema
-- =====================================================================================

-- MÓDULO: MATRÍCULA - Tabla ALUMNOS
CREATE TABLE bom_matricula.alumnos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    apellido_paterno VARCHAR2(50) NOT NULL,
    apellido_materno VARCHAR2(50),
    dni VARCHAR2(20) UNIQUE NOT NULL,
    fecha_ingreso DATE NOT NULL,
    grado VARCHAR2(20) NOT NULL,
    seccion VARCHAR2(10)
);

-- MÓDULO: CALIFICACIONES - Tabla NOTAS
CREATE TABLE bom_calificaciones.notas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id NUMBER NOT NULL,
    evaluacion VARCHAR2(100) NOT NULL,
    valor NUMBER(4,2) NOT NULL,
    ponderacion NUMBER(3) NOT NULL DEFAULT 10,
    fecha_registro DATE DEFAULT SYSDATE NOT NULL,
    estado VARCHAR2(20) DEFAULT 'REGISTRADA' NOT NULL
);

-- MÓDULO: SEGURIDAD - Tabla USUARIOS
CREATE TABLE bom_seguridad.usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    rol VARCHAR2(20) DEFAULT 'ALUMNO' NOT NULL,
    estado VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL
);

-- Insertar usuario admin por defecto (ya existe en la BD Free)
INSERT INTO bom_seguridad.usuarios (username, password_hash, rol, estado)
VALUES ('admin', 'admin123', 'ADMIN', 'ACTIVO');
EOF
echo "SQL script updated"