ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER BOM_SEGURIDAD IDENTIFIED BY 123456;
CREATE USER BOM_ACADEMICO IDENTIFIED BY 123456;
CREATE USER BOM_HORARIOS IDENTIFIED BY 123456;
CREATE USER BOM_MATRICULAS IDENTIFIED BY 123456;
CREATE USER BOM_TAREAS IDENTIFIED BY 123456;
CREATE USER BOM_ASISTENCIA IDENTIFIED BY 123456;
CREATE USER BOM_AVISOS IDENTIFIED BY 123456;

ALTER USER BOM_SEGURIDAD QUOTA UNLIMITED ON users;
ALTER USER BOM_ACADEMICO QUOTA UNLIMITED ON users;
ALTER USER BOM_HORARIOS QUOTA UNLIMITED ON users;
ALTER USER BOM_MATRICULAS QUOTA UNLIMITED ON users;
ALTER USER BOM_TAREAS QUOTA UNLIMITED ON users;
ALTER USER BOM_ASISTENCIA QUOTA UNLIMITED ON users;
ALTER USER BOM_AVISOS QUOTA UNLIMITED ON users;

GRANT CREATE SESSION, RESOURCE TO BOM_SEGURIDAD;
GRANT CREATE SESSION, RESOURCE TO BOM_ACADEMICO;
GRANT CREATE SESSION, RESOURCE TO BOM_HORARIOS;
GRANT CREATE SESSION, RESOURCE TO BOM_MATRICULAS;
GRANT CREATE SESSION, RESOURCE TO BOM_TAREAS;
GRANT CREATE SESSION, RESOURCE TO BOM_ASISTENCIA;
GRANT CREATE SESSION, RESOURCE TO BOM_AVISOS;

EXIT;
