ALTER SESSION SET CONTAINER = FREEPDB1;

GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_SEGURIDAD.USUARIOS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_ACADEMICO.CARRERAS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_ACADEMICO.CICLOS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_ACADEMICO.AULAS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_ACADEMICO.CURSOS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_HORARIOS.HORARIOS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_MATRICULAS.MATRICULAS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_TAREAS.TAREAS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_TAREAS.ENTREGAS TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_ASISTENCIA.CLASES TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_ASISTENCIA.ASISTENCIA TO BOMERP_APP;
GRANT SELECT, INSERT, UPDATE, DELETE ON BOM_AVISOS.AVISOS TO BOMERP_APP;

EXIT;
